[cities]
Atlanta = 5710795
Austin = 2000860
Baltimore = 2797407
Boston = 4774321
Charlotte = 2426363
Chicago = 9551031
Cincinnati = 2157719
Cleveland = 2060810
Columbus = 2021632
Dallas = 7102796
Detroit = 4302043
Denver = 2814330
Houston = 6656947
Indianapolis = 1988817
Kansas_City = 2087471
Las_Vegas = 2114801
Los_Angeles = 13340068
Miami = 6012331
Milwaukee = 1575747
Minneapolis = 3524583
Nashville = 1830345
New_York = 20182305
Norfolk = 1724876
Orlando = 2387138
Philadelphia = 6069875
Phoenix = 4574531
Portland = 2389228
Pittsburgh = 2353045
Providence = 1613070
Sacramento = 2274194
San_Antonio = 2384075
San_Bernardino = 4489159
San_Diego = 3299521
San_Francisco = 4656132
San_Jose = 1976836
Seattle = 3733580
St_Louis = 2811588
Tampa = 2975225
Washington_DC = 6097684

[states]
Alabama        = { electors =  9, pop =  4_858_979 }
Alaska         = { electors =  3, pop =    738_432 }
Arizona        = { electors = 11, pop =  6_828_065 }
Arkansas       = { electors =  6, pop =  2_978_204 }
California     = { electors = 55, pop = 39_144_818 }
Colorado       = { electors =  9, pop =  5_456_574 }
Connecticut    = { electors =  7, pop =  3_590_886 }
DC             = { electors =  3, pop =    672_228 }
Delaware       = { electors =  3, pop =    945_934 }
Florida        = { electors = 29, pop = 20_271_272 }
Georgia        = { electors = 16, pop = 10_214_860 }
Hawaii         = { electors =  4, pop =  1_431_603 }
Idaho          = { electors =  4, pop =  1_654_930 }
Illinois       = { electors = 20, pop = 12_859_995 }
Indiana        = { electors = 11, pop =  6_619_680 }
Iowa           = { electors =  6, pop =  3_123_899 }
Kansas         = { electors =  6, pop =  2_911_641 }
Kentucky       = { electors =  8, pop =  4_425_092 }
Louisiana      = { electors =  8, pop =  4_670_724 }
Maine          = { electors =  4, pop =  1_329_328 }
Maryland       = { electors = 10, pop =  6_006_401 }
Massachusetts  = { electors = 11, pop =  6_794_422 }
Michigan       = { electors = 16, pop =  9_922_576 }
Minnesota      = { electors = 10, pop =  5_489_594 }
Mississippi    = { electors =  6, pop =  2_992_333 }
Missouri       = { electors = 10, pop =  6_083_672 }
Montana        = { electors =  3, pop =  1_032_949 }
Nebraska       = { electors =  5, pop =  1_826_341 }
Nevada         = { electors =  6, pop =  2_700_691 }
New_Hampshire  = { electors =  4, pop =  1_316_466 }
New_Jersey     = { electors = 14, pop =  8_791_936 }
New_Mexico     = { electors =  5, pop =  2_059_192 }
New_York       = { electors = 29, pop = 19_378_087 }
North_Carolina = { electors = 15, pop =  9_535_692 }
North_Dakota   = { electors =  3, pop =    672_591 }
Ohio           = { electors = 18, pop = 11_536_725 }
Oklahoma       = { electors =  7, pop =  3_751_616 }
Oregon         = { electors =  7, pop =  3_831_073 }
Pennsylvania   = { electors = 20, pop = 12_702_887 }
Rhode_Island   = { electors =  4, pop =  1_052_931 }
South_Carolina = { electors =  9, pop =  4_625_401 }
South_Dakota   = { electors =  3, pop =    814_191 }
Tennessee      = { electors = 11, pop =  6_346_275 }
Texas          = { electors = 38, pop = 25_146_105 }
Utah           = { electors =  6, pop =  2_763_888 }
Vermont        = { electors =  3, pop =    625_745 }
Virginia       = { electors = 13, pop =  8_001_045 }
Washington     = { electors = 12, pop =  6_724_543 }
West_Virginia  = { electors =  5, pop =  1_853_011 }
Wisconsin      = { electors = 10, pop =  5_687_289 }
Wyoming        = { electors =  3, pop =    563_767 }
